# .rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/initializers/**/*"
    - "config/puma.rb"
    - "public/**/*"
    - "storage/**/*"

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  Enabled: false
