# .rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/initializers/**/*"
    - "config/puma.rb"
    - "public/**/*"
    - "storage/**/*"

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 15

# 追加されたルール
Layout/IndentationWidth:
  Width: 4

Layout/IndentationConsistency:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Style/GlobalVars:
  Enabled: false
