apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/te2wow/containerTutorial.git'
    targetRevision: HEAD
    path: './service_b'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
