apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: tetsuwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b-container
        image: nginx:1.27.0
        ports:
        - containerPort: 80
