apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: tetsuwo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b-container
        image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/service-b-image:latest
        ports:
        - containerPort: 3000
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "service-b"
      imagePullSecrets:
        - name: ghcr-secret

