# .rubocop.yml
AllCops:
  NewCops: enable # 新しいルールを有効化または無効化

# 特定のCopを無効化
Style/StringLiterals:
  Enabled: false

# 警告を発生させないようにするルールの緩和
Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 15

Exclude:
   - "Gemfile"
