apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: tetsuwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-container
        image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/service-a-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "tetsuwo-service-a"
      imagePullSecrets:
        - name: ghcr-secret
