apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: tetsuwo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-container
        image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/service-a-image:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
